// <auto-generated />
namespace WebAppSportsLeagueTestTask.WEB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SetDirectorFullName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SetDirectorFullName));
        
        string IMigrationMetadata.Id
        {
            get { return "201906261751032_Set Director FullName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
